# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laminar_gui_v3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QCheckBox
from mplwidget import MplWidget

class Ui_mainWidget(object):
    def setupUi(self, mainWidget):
        self.layerBorders = {'BS/1': -800, '3/4': 0, '4/5':200,
                             '6/6d': 800, '5d/4d': 1600, '4d/3d': 1800, '3d/Bd': 2600,
                             '6/WM':800, 'WM/HC':2700}
        mainWidget.setObjectName("mainWidget")
        mainWidget.resize(1150, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWidget.sizePolicy().hasHeightForWidth())
        mainWidget.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(mainWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.templategroupBox = QtWidgets.QGroupBox(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templategroupBox.sizePolicy().hasHeightForWidth())
        self.templategroupBox.setSizePolicy(sizePolicy)
        self.templategroupBox.setMinimumSize(QtCore.QSize(150, 65))
        self.templategroupBox.setObjectName("templategroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.templategroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tempPSDradioButton = QtWidgets.QRadioButton(self.templategroupBox)
        self.tempPSDradioButton.setMinimumSize(QtCore.QSize(20, 20))
        self.tempPSDradioButton.setChecked(True)
        self.tempPSDradioButton.setObjectName("tempPSDradioButton")
        self.horizontalLayout.addWidget(self.tempPSDradioButton)
        self.tempCSDradioButton = QtWidgets.QRadioButton(self.templategroupBox)
        self.tempCSDradioButton.setMinimumSize(QtCore.QSize(20, 20))
        self.tempCSDradioButton.setObjectName("tempCSDradioButton")
        self.horizontalLayout.addWidget(self.tempCSDradioButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.templategroupBox, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.siteselectgroupBox = QtWidgets.QGroupBox(mainWidget)
        self.siteselectgroupBox.setMinimumSize(QtCore.QSize(0, 70))
        self.siteselectgroupBox.setObjectName("siteselectgroupBox")
        self.layoutWidget = QtWidgets.QWidget(self.siteselectgroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 25, 281, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.SiteselectLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.SiteselectLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.SiteselectLayout.setContentsMargins(0, 0, 0, 0)
        self.SiteselectLayout.setSpacing(6)
        self.SiteselectLayout.setObjectName("SiteselectLayout")
        self.siteactivecheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.siteactivecheckBox.setChecked(True)
        self.siteactivecheckBox.setObjectName("siteactivecheckBox")
        self.SiteselectLayout.addWidget(self.siteactivecheckBox)
        self.animalcomboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animalcomboBox.sizePolicy().hasHeightForWidth())
        self.animalcomboBox.setSizePolicy(sizePolicy)
        self.animalcomboBox.setObjectName("animalcomboBox")
        self.SiteselectLayout.addWidget(self.animalcomboBox)
        self.sitecomboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sitecomboBox.sizePolicy().hasHeightForWidth())
        self.sitecomboBox.setSizePolicy(sizePolicy)
        self.sitecomboBox.setObjectName("sitecomboBox")
        self.SiteselectLayout.addWidget(self.sitecomboBox, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.siteselectgroupBox)
        self.siteList = QtWidgets.QTreeWidget(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.siteList.sizePolicy().hasHeightForWidth())
        self.siteList.setSizePolicy(sizePolicy)
        self.siteList.setMinimumSize(QtCore.QSize(300, 300))
        self.siteList.setColumnCount(3)
        self.siteList.setColumnWidth(0,200)
        self.siteList.setColumnWidth(1,50)
        #self.siteList.setColumnWidth(2,60)
        #self.siteList.setColumnWidth(3,40)

        self.siteList.setObjectName("siteList")
        self.verticalLayout.addWidget(self.siteList)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sitealigncheckBox = QtWidgets.QCheckBox(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sitealigncheckBox.sizePolicy().hasHeightForWidth())
        self.sitealigncheckBox.setSizePolicy(sizePolicy)
        self.sitealigncheckBox.setObjectName("sitealigncheckBox")
        self.horizontalLayout_4.addWidget(self.sitealigncheckBox)
        self.siteplotpushButton = QtWidgets.QPushButton(mainWidget)
        self.siteplotpushButton.setObjectName("siteplotpushButton")
        self.horizontalLayout_4.addWidget(self.siteplotpushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 3, 1)
        self.siteCanvas = MplWidget(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.siteCanvas.sizePolicy().hasHeightForWidth())
        self.siteCanvas.setSizePolicy(sizePolicy)
        self.siteCanvas.setMinimumSize(QtCore.QSize(400, 200))
        self.siteCanvas.setObjectName("siteCanvas")
        self.gridLayout.addWidget(self.siteCanvas, 1, 2, 1, 1)
        self.sitegroupBox = QtWidgets.QGroupBox(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sitegroupBox.sizePolicy().hasHeightForWidth())
        self.sitegroupBox.setSizePolicy(sizePolicy)
        self.sitegroupBox.setMinimumSize(QtCore.QSize(150, 65))
        self.sitegroupBox.setObjectName("sitegroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sitegroupBox)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sitePSDradioButton = QtWidgets.QRadioButton(self.sitegroupBox)
        self.sitePSDradioButton.setMinimumSize(QtCore.QSize(20, 20))
        self.sitePSDradioButton.setChecked(True)
        self.sitePSDradioButton.setObjectName("sitePSDradioButton")
        self.horizontalLayout_2.addWidget(self.sitePSDradioButton)
        self.siteCSDradioButton = QtWidgets.QRadioButton(self.sitegroupBox)
        self.siteCSDradioButton.setMinimumSize(QtCore.QSize(20, 20))
        self.siteCSDradioButton.setObjectName("siteCSDradioButton")
        self.horizontalLayout_2.addWidget(self.siteCSDradioButton)
        self.siteCOHradioButton = QtWidgets.QRadioButton(self.sitegroupBox)
        self.siteCOHradioButton.setMinimumSize(QtCore.QSize(20, 20))
        self.siteCOHradioButton.setObjectName("siteCOHradioButton")
        self.horizontalLayout_2.addWidget(self.siteCOHradioButton)
        self.siteERPradioButton = QtWidgets.QRadioButton(self.sitegroupBox)
        self.siteERPradioButton.setMinimumSize(QtCore.QSize(20, 20))
        self.siteERPradioButton.setObjectName("siteERPradioButton")
        self.horizontalLayout_2.addWidget(self.siteERPradioButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.sitegroupBox, 0, 2, 1, 1)
        self.templateCanvas = MplWidget(mainWidget)
        self.templateCanvas.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templateCanvas.sizePolicy().hasHeightForWidth())
        self.templateCanvas.setSizePolicy(sizePolicy)
        self.templateCanvas.setMinimumSize(QtCore.QSize(400, 200))
        self.templateCanvas.setObjectName("templateCanvas")
        self.gridLayout.addWidget(self.templateCanvas, 1, 1, 1, 1)
        self.plotsettingstabWidget = QtWidgets.QTabWidget(mainWidget)
        self.plotsettingstabWidget.setMinimumSize(QtCore.QSize(220, 0))
        self.plotsettingstabWidget.setObjectName("plotsettingstabWidget")
        self.Markers = QtWidgets.QWidget()
        self.Markers.setObjectName("Markers")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Markers)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.landmarkgroupBox = QtWidgets.QGroupBox(self.Markers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landmarkgroupBox.sizePolicy().hasHeightForWidth())
        self.landmarkgroupBox.setSizePolicy(sizePolicy)
        self.landmarkgroupBox.setMinimumSize(QtCore.QSize(0, 300))
        self.landmarkgroupBox.setObjectName("landmarkgroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.landmarkgroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.templatelandmarkcheckBox = QtWidgets.QCheckBox(self.landmarkgroupBox)
        self.templatelandmarkcheckBox.setChecked(True)
        self.templatelandmarkcheckBox.setObjectName("templatelandmarkcheckBox")
        self.verticalLayout_6.addWidget(self.templatelandmarkcheckBox)
        self.sitelandmarkcheckBox = QtWidgets.QCheckBox(self.landmarkgroupBox)
        self.sitelandmarkcheckBox.setChecked(True)
        self.sitelandmarkcheckBox.setObjectName("sitelandmarkcheckBox")
        self.verticalLayout_6.addWidget(self.sitelandmarkcheckBox)
        self.label_2 = QtWidgets.QLabel(self.landmarkgroupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.landmarkscrollArea = QtWidgets.QScrollArea(self.landmarkgroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landmarkscrollArea.sizePolicy().hasHeightForWidth())
        self.landmarkscrollArea.setSizePolicy(sizePolicy)
        self.landmarkscrollArea.setWidgetResizable(True)
        self.landmarkscrollArea.setObjectName("landmarkscrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 172, 414))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layerCheckBoxes = {f'{l}': '' for l in list(self.layerBorders.keys())}
        for layer in self.layerCheckBoxes.keys():
            checkbox = QCheckBox(layer)
            self.layerCheckBoxes[layer] = checkbox
            self.verticalLayout_4.addWidget(checkbox)
        self.landmarkscrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.landmarkscrollArea)
        self.label = QtWidgets.QLabel(self.landmarkgroupBox)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.landmarkcomboBox = QtWidgets.QComboBox(self.landmarkgroupBox)
        self.landmarkcomboBox.setObjectName("landmarkcomboBox")
        self.verticalLayout_6.addWidget(self.landmarkcomboBox)
        self.arealabel = QtWidgets.QLabel(self.landmarkgroupBox)
        self.arealabel.setObjectName("arealabel")
        self.verticalLayout_6.addWidget(self.arealabel)
        self.areatext = QtWidgets.QTextEdit(self.landmarkcomboBox)
        self.areatext.setObjectName("areatext")
        self.areatext.setMaximumSize(QtCore.QSize(180, 30))
        self.verticalLayout_6.addWidget(self.areatext)
        self.arealabeldeep = QtWidgets.QLabel(self.landmarkgroupBox)
        self.arealabeldeep.setObjectName("arealabeldeep")
        self.verticalLayout_6.addWidget(self.arealabeldeep)
        self.areatextdeep = QtWidgets.QTextEdit(self.landmarkcomboBox)
        self.areatextdeep.setObjectName("areatextdeep")
        self.verticalLayout_6.addWidget(self.areatextdeep)
        self.areatextdeep.setMaximumSize(QtCore.QSize(180, 30))
        self.lineresetButton = QtWidgets.QPushButton(self.landmarkgroupBox)
        self.lineresetButton.setObjectName("lineresetButton")
        self.verticalLayout_6.addWidget(self.lineresetButton )
        self.resetlandmarkspushButton = QtWidgets.QPushButton(self.landmarkgroupBox)
        self.resetlandmarkspushButton.setObjectName("resetlandmarkspushButton")
        self.verticalLayout_6.addWidget(self.resetlandmarkspushButton)
        self.assignButton = QtWidgets.QPushButton(self.landmarkgroupBox)
        self.assignButton.setObjectName("assignButton")
        self.verticalLayout_6.addWidget(self.assignButton)
        self.verticalLayout_7.addWidget(self.landmarkgroupBox)
        self.plotsettingstabWidget.addTab(self.Markers, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.normalizationgroupBox = QtWidgets.QGroupBox(self.Settings)
        self.normalizationgroupBox.setGeometry(QtCore.QRect(9, 9, 191, 117))
        self.normalizationgroupBox.setObjectName("normalizationgroupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.normalizationgroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tempmaxnormradioButton = QtWidgets.QRadioButton(self.normalizationgroupBox)
        self.tempmaxnormradioButton.setObjectName("tempmaxnormradioButton")
        self.verticalLayout_8.addWidget(self.tempmaxnormradioButton)
        self.sitemaxnormradioButton = QtWidgets.QRadioButton(self.normalizationgroupBox)
        self.sitemaxnormradioButton.setObjectName("sitemaxnormradioButton")
        self.verticalLayout_8.addWidget(self.sitemaxnormradioButton)
        self.localnormradioButton = QtWidgets.QRadioButton(self.normalizationgroupBox)
        self.localnormradioButton.setObjectName("localnormradioButton")
        self.verticalLayout_8.addWidget(self.localnormradioButton)
        self.localnormradioButton.setChecked(True)
        self.nonormradioButton = QtWidgets.QRadioButton(self.normalizationgroupBox)
        self.nonormradioButton.setObjectName("nonormradioButton")
        self.verticalLayout_8.addWidget(self.nonormradioButton)
        self.figsavegroupBox = QtWidgets.QGroupBox(self.Settings)
        self.figsavegroupBox.setGeometry(QtCore.QRect(9, 139, 191, 151))
        self.figsavegroupBox.setObjectName("figsavegroupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.figsavegroupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 29, 171, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.figsavelabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.figsavelabel.setObjectName("figsavelabel")
        self.verticalLayout_9.addWidget(self.figsavelabel)
        self.figsavelineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.figsavelineEdit.setObjectName("figsavelineEdit")
        self.verticalLayout_9.addWidget(self.figsavelineEdit)
        self.figsavecheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.figsavecheckBox.setObjectName("figsavecheckBox")
        self.verticalLayout_9.addWidget(self.figsavecheckBox)
        self.figsavepushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.figsavepushButton.setObjectName("figsavepushButton")
        self.verticalLayout_9.addWidget(self.figsavepushButton)
        self.plotsettingstabWidget.addTab(self.Settings, "")
        self.gridLayout.addWidget(self.plotsettingstabWidget, 0, 3, 3, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        # self.verticalLayout_6.addWidget(self.assignButton)
        # self.verticalLayout_7.addWidget(self.landmarkgroupBox)
        # self.plotsettingstabWidget.addTab(self.Markers, "")
        # self.tab_4 = QtWidgets.QWidget()
        # self.tab_4.setObjectName("tab_4")
        # self.normalizationgroupBox = QtWidgets.QGroupBox(self.tab_4)
        # self.normalizationgroupBox.setGeometry(QtCore.QRect(9, 9, 191, 117))
        # self.normalizationgroupBox.setObjectName("normalizationgroupBox")
        # self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.normalizationgroupBox)
        # self.verticalLayout_8.setObjectName("verticalLayout_8")
        # self.tempmaxnormradioButton = QtWidgets.QRadioButton(self.normalizationgroupBox)
        # self.tempmaxnormradioButton.setObjectName("tempmaxnormradioButton")
        # self.tempmaxnormradioButton.setChecked(True)
        # self.verticalLayout_8.addWidget(self.tempmaxnormradioButton)
        # self.sitemaxnormradioButton = QtWidgets.QRadioButton(self.normalizationgroupBox)
        # self.sitemaxnormradioButton.setObjectName("sitemaxnormradioButton")
        # self.verticalLayout_8.addWidget(self.sitemaxnormradioButton)
        # self.localnormradioButton = QtWidgets.QRadioButton(self.normalizationgroupBox)
        # self.localnormradioButton.setObjectName("localnormradioButton")
        # self.verticalLayout_8.addWidget(self.localnormradioButton)
        # self.nonormradioButton = QtWidgets.QRadioButton(self.normalizationgroupBox)
        # self.nonormradioButton.setObjectName("nonormradioButton")
        # self.verticalLayout_8.addWidget(self.nonormradioButton)
        # self.plotsettingstabWidget.addTab(self.tab_4, "")
        # self.figsavegroupBox = QtWidgets.QGroupBox(self.tab_4)
        # self.figsavegroupBox.setObjectName("figsavegroupBox")
        # self.verticalLayout_8.addWidget(self.figsavegroupBox)
        # self.figsavecheckBox = QtWidgets.QCheckBox(self.figsavegroupBox)
        # self.figsavecheckBox.setObjectName("figsavecheckBox")
        # self.verticalLayout_8.addWidget(self.figsavecheckBox)
        # self.figsavepushButton = QtWidgets.QPushButton(self.figsavegroupBox)
        # self.figsavepushButton.setObjectName("figsavepushButton")
        # self.verticalLayout_8.addWidget(self.figsavepushButton)
        #
        # self.gridLayout.addWidget(self.plotsettingstabWidget, 0, 3, 3, 2)
        # self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(mainWidget)
        self.plotsettingstabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidget):
        _translate = QtCore.QCoreApplication.translate
        mainWidget.setWindowTitle(_translate("mainWidget", "Laminar GUI"))
        self.templategroupBox.setTitle(_translate("mainWidget", "Template"))
        self.tempPSDradioButton.setText(_translate("mainWidget", "PSD"))
        self.tempCSDradioButton.setText(_translate("mainWidget", "CSD"))
        self.siteselectgroupBox.setTitle(_translate("mainWidget", "Site Select"))
        self.siteactivecheckBox.setText(_translate("mainWidget", "Active"))
        self.siteList.headerItem().setText(0, _translate("mainWidget", "File Name"))
        self.siteList.headerItem().setText(1, _translate("mainWidget", "Raw ID"))
        self.siteList.headerItem().setText(2, _translate("mainWidget", "DB"))
        self.sitealigncheckBox.setText(_translate("mainWidget", "Align template"))
        self.sitegroupBox.setTitle(_translate("mainWidget", "Site"))
        self.sitePSDradioButton.setText(_translate("mainWidget", "PSD"))
        self.siteCSDradioButton.setText(_translate("mainWidget", "CSD"))
        self.siteCOHradioButton.setText(_translate("mainWidget", "COH"))
        self.siteERPradioButton.setText(_translate("mainWidget", "ERP"))
        self.landmarkgroupBox.setTitle(_translate("mainWidget", "Landmark tools"))
        self.templatelandmarkcheckBox.setText(_translate("mainWidget", "Template landmarks"))
        self.sitelandmarkcheckBox.setText(_translate("mainWidget", "Site landmarks"))
        self.label_2.setText(_translate("mainWidget", "Site landmarks"))
        self.arealabel.setText(_translate("mainWidget", "Cortical area"))
        self.arealabeldeep.setText(_translate("mainWidget", "Deep area"))
        self.label.setText(_translate("mainWidget", "Active landmark"))
        self.lineresetButton.setText(_translate("mainWidget", "Reset current"))
        self.resetlandmarkspushButton.setText(_translate("mainWidget", "Reset all"))
        self.assignButton.setText(_translate("mainWidget", "Assign"))
        self.plotsettingstabWidget.setTabText(self.plotsettingstabWidget.indexOf(self.Markers), _translate("mainWidget", "Plot Markers"))
        self.normalizationgroupBox.setTitle(_translate("mainWidget", "Normalization"))
        self.tempmaxnormradioButton.setText(_translate("mainWidget", "Template max"))
        self.sitemaxnormradioButton.setText(_translate("mainWidget", "Site max"))
        self.localnormradioButton.setText(_translate("mainWidget", "Local max"))
        self.nonormradioButton.setText(_translate("mainWidget", "None"))
        self.plotsettingstabWidget.setTabText(self.plotsettingstabWidget.indexOf(self.Settings), _translate("mainWidget", "Plot Settings"))
        self.siteplotpushButton.setText(_translate("mainWidget", "Plot selected"))
        self.figsavegroupBox.setTitle(_translate("mainWidget", "Save current plot"))
        self.figsavecheckBox.setText(_translate("mainWidget", "Save fig?"))
        self.figsavepushButton.setText(_translate("mainWidget", "Save"))
        self.figsavelabel.setText(_translate("mainWidget", "Path"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWidget = QtWidgets.QWidget()
    ui = Ui_mainWidget()
    ui.setupUi(mainWidget)
    mainWidget.show()
    sys.exit(app.exec_())