# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laminar_gui_v2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from mplwidget import MplWidget
from PyQt5.QtWidgets import QCheckBox

class Ui_mainWidget(object):
    def setupUi(self, mainWidget):
        self.layerBorders = ['BS/1', '1/2', '2/3', '3/4', '4/5', '5/6']
        mainWidget.setObjectName("mainWidget")
        mainWidget.resize(988, 656)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWidget.sizePolicy().hasHeightForWidth())
        mainWidget.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(mainWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.sitegroupBox = QtWidgets.QGroupBox(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sitegroupBox.sizePolicy().hasHeightForWidth())
        self.sitegroupBox.setSizePolicy(sizePolicy)
        self.sitegroupBox.setMinimumSize(QtCore.QSize(30, 180))
        self.sitegroupBox.setObjectName("sitegroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sitegroupBox)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sitePSDradioButton = QtWidgets.QRadioButton(self.sitegroupBox)
        self.sitePSDradioButton.setMinimumSize(QtCore.QSize(20, 20))
        self.sitePSDradioButton.setObjectName("sitePSDradioButton")
        self.horizontalLayout_2.addWidget(self.sitePSDradioButton)
        self.siteCSDradioButton = QtWidgets.QRadioButton(self.sitegroupBox)
        self.siteCSDradioButton.setMinimumSize(QtCore.QSize(20, 20))
        self.siteCSDradioButton.setObjectName("siteCSDradioButton")
        self.horizontalLayout_2.addWidget(self.siteCSDradioButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.landmarkgroupBox = QtWidgets.QGroupBox(self.sitegroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landmarkgroupBox.sizePolicy().hasHeightForWidth())
        self.landmarkgroupBox.setSizePolicy(sizePolicy)
        self.landmarkgroupBox.setMinimumSize(QtCore.QSize(0, 120))
        self.landmarkgroupBox.setObjectName("landmarkgroupBox")
        self.landmarkscrollArea = QtWidgets.QScrollArea(self.landmarkgroupBox)
        self.landmarkscrollArea.setGeometry(QtCore.QRect(10, 30, 281, 80))
        self.landmarkscrollArea.setWidgetResizable(True)
        self.landmarkscrollArea.setObjectName("landmarkscrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 279, 50))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layerCheckBoxes = {f'{l}': '' for l in self.layerBorders}
        for layer in self.layerCheckBoxes.keys():
            checkbox = QCheckBox(layer)
            self.layerCheckBoxes[layer] = checkbox
            self.verticalLayout_4.addWidget(checkbox)
        self.landmarkscrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.landmarkgroupBox)
        self.landmarkcomboBox = QtWidgets.QComboBox(self.sitegroupBox)
        self.landmarkcomboBox.setObjectName("landmarkcomboBox")
        self.verticalLayout_3.addWidget(self.landmarkcomboBox)
        self.gridLayout.addWidget(self.sitegroupBox, 0, 2, 1, 1, QtCore.Qt.AlignTop)
        self.templategroupBox = QtWidgets.QGroupBox(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templategroupBox.sizePolicy().hasHeightForWidth())
        self.templategroupBox.setSizePolicy(sizePolicy)
        self.templategroupBox.setMinimumSize(QtCore.QSize(30, 60))
        self.templategroupBox.setObjectName("templategroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.templategroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tempPSDradioButton = QtWidgets.QRadioButton(self.templategroupBox)
        self.tempPSDradioButton.setMinimumSize(QtCore.QSize(20, 20))
        self.tempPSDradioButton.setObjectName("tempPSDradioButton")
        self.horizontalLayout.addWidget(self.tempPSDradioButton)
        self.tempCSDradioButton = QtWidgets.QRadioButton(self.templategroupBox)
        self.tempCSDradioButton.setMinimumSize(QtCore.QSize(20, 20))
        self.tempCSDradioButton.setObjectName("tempCSDradioButton")
        self.horizontalLayout.addWidget(self.tempCSDradioButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.templategroupBox, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.siteCanvas = MplWidget(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.siteCanvas.sizePolicy().hasHeightForWidth())
        self.siteCanvas.setSizePolicy(sizePolicy)
        self.siteCanvas.setObjectName("siteCanvas")
        self.gridLayout.addWidget(self.siteCanvas, 1, 2, 3, 1)
        self.templateCanvas = MplWidget(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templateCanvas.sizePolicy().hasHeightForWidth())
        self.templateCanvas.setSizePolicy(sizePolicy)
        self.templateCanvas.setObjectName("templateCanvas")
        self.gridLayout.addWidget(self.templateCanvas, 1, 1, 3, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.siteselectgroupBox = QtWidgets.QGroupBox(mainWidget)
        self.siteselectgroupBox.setMinimumSize(QtCore.QSize(0, 70))
        self.siteselectgroupBox.setObjectName("siteselectgroupBox")
        self.layoutWidget = QtWidgets.QWidget(self.siteselectgroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 25, 281, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.SiteselectLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.SiteselectLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.SiteselectLayout.setContentsMargins(0, 0, 0, 0)
        self.SiteselectLayout.setSpacing(6)
        self.SiteselectLayout.setObjectName("SiteselectLayout")
        self.animalcomboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animalcomboBox.sizePolicy().hasHeightForWidth())
        self.animalcomboBox.setSizePolicy(sizePolicy)
        self.animalcomboBox.setObjectName("animalcomboBox")
        self.SiteselectLayout.addWidget(self.animalcomboBox)
        self.sitecomboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sitecomboBox.sizePolicy().hasHeightForWidth())
        self.sitecomboBox.setSizePolicy(sizePolicy)
        self.sitecomboBox.setObjectName("sitecomboBox")
        self.SiteselectLayout.addWidget(self.sitecomboBox, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.siteselectgroupBox)
        self.siteList = QtWidgets.QTreeWidget(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.siteList.sizePolicy().hasHeightForWidth())
        self.siteList.setSizePolicy(sizePolicy)
        self.siteList.setMinimumSize(QtCore.QSize(300, 500))
        self.siteList.setColumnCount(3)
        self.siteList.setObjectName("siteList")
        self.verticalLayout.addWidget(self.siteList)
        self.sitepushButton = QtWidgets.QPushButton(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sitepushButton.sizePolicy().hasHeightForWidth())
        self.sitepushButton.setSizePolicy(sizePolicy)
        self.sitepushButton.setObjectName("sitepushButton")
        self.verticalLayout.addWidget(self.sitepushButton)
        self.assignButton = QtWidgets.QPushButton(mainWidget)
        self.assignButton.setObjectName("assignButton")
        self.verticalLayout.addWidget(self.assignButton)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 4, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(mainWidget)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidget):
        _translate = QtCore.QCoreApplication.translate
        mainWidget.setWindowTitle(_translate("mainWidget", "Cortical Layer GUI"))
        self.sitegroupBox.setTitle(_translate("mainWidget", "Site"))
        self.sitePSDradioButton.setText(_translate("mainWidget", "PSD"))
        self.siteCSDradioButton.setText(_translate("mainWidget", "CSD"))
        self.landmarkgroupBox.setTitle(_translate("mainWidget", "Landmarks"))
        self.templategroupBox.setTitle(_translate("mainWidget", "Template"))
        self.tempPSDradioButton.setText(_translate("mainWidget", "PSD"))
        self.tempCSDradioButton.setText(_translate("mainWidget", "CSD"))
        self.siteselectgroupBox.setTitle(_translate("mainWidget", "Site Select"))
        self.siteList.headerItem().setText(0, _translate("mainWidget", "File Name"))
        self.siteList.headerItem().setText(1, _translate("mainWidget", "Landmarks"))
        self.siteList.headerItem().setText(2, _translate("mainWidget", "Values"))
        self.sitepushButton.setText(_translate("mainWidget", "Load Selected"))
        self.assignButton.setText(_translate("mainWidget", "Assign Selected"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWidget = QtWidgets.QWidget()
    ui = Ui_mainWidget()
    ui.setupUi(mainWidget)
    mainWidget.show()
    sys.exit(app.exec_())